-- MySQL Script generated by MySQL Workbench
-- Wed Mar  2 09:54:10 2022
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shopping_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopping_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopping_db` DEFAULT CHARACTER SET utf8 ;
USE `shopping_db` ;

-- -----------------------------------------------------
-- Table `shopping_db`.`Lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Lang` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `code` VARCHAR(10) NULL,
  `flag` VARCHAR(255) NULL,
  `is_extra_id` INT NULL,
  `file` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Currency` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(10) NULL,
  `symbol` VARCHAR(5) NULL,
  `change_rate` DOUBLE NULL,
  `is_default` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `shopping_db`.`Vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Vendor` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `short_description` VARCHAR(150) NULL,
  `long_description` TEXT NULL,
  `phone1` VARCHAR(15) NULL,
  `phone2` VARCHAR(15) NULL,
  `phone3` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  `icon_img` VARCHAR(255) NULL,
  `cover_img` VARCHAR(255) NULL,
  `social_fb` VARCHAR(145) NULL,
  `social_yt` VARCHAR(145) NULL,
  `social_tw` VARCHAR(145) NULL,
  `social_tk` VARCHAR(145) NULL,
  `social_ig` VARCHAR(145) NULL,
  `is_active` TINYINT NULL,
  `is_page_visible` TINYINT NULL,
  `is_product_visible` TINYINT NULL,
  `is_maintenance` TINYINT NULL,
  `id_admin` INT NULL,
  `id_vendor_category` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Brand` (
  `id` INT NOT NULL,
  `name` VARCHAR(145) NULL,
  `image` VARCHAR(255) NULL,
  `icom_img` VARCHAR(255) NULL,
  `slug` VARCHAR(145) NULL,
  `description` VARCHAR(255) NULL,
  `created_by` INT NULL,
  `created_datetime` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_datetime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Product_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Product_Category` (
  `id` INT NOT NULL,
  `name` VARCHAR(145) NULL,
  `image` VARCHAR(255) NULL,
  `icon_img` VARCHAR(255) NULL,
  `slug` VARCHAR(145) NULL,
  `desciption` VARCHAR(255) NULL,
  `created_by` INT NULL,
  `created_datetime` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_datetime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Page` (
  `id` INT NOT NULL,
  `title` VARCHAR(145) NULL,
  `subtitle` VARCHAR(145) NULL,
  `slug` VARCHAR(145) NULL,
  `content_html` TEXT NULL,
  `created_by` INT NULL,
  `created_datetime` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_datetime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Vendor_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Vendor_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(145) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`User` (
  `id` INT NOT NULL,
  `last_name` VARCHAR(100) NULL,
  `first_name` VARCHAR(100) NULL,
  `phone` VARCHAR(15) NULL,
  `password` VARCHAR(45) NULL,
  `password_salt` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `adresse` VARCHAR(155) NULL,
  `adresse2` VARCHAR(155) NULL,
  `aff_code` VARCHAR(45) NULL,
  `aff_by` INT NULL,
  `is_active` TINYINT NULL,
  `is_confirmed_email` TINYINT NULL,
  `is_confirmed_phone` TINYINT NULL,
  `id_customer_category` INT NULL,
  `registered_datetime` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_datetime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Wishlist` (
  `id` INT NOT NULL,
  `id_customer` INT NULL,
  `id_product` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Country` (
  `id` INT NOT NULL,
  `name` VARCHAR(155) NULL,
  `flag_img` VARCHAR(255) NULL,
  `iso_code` VARCHAR(5) NULL,
  `phone_code` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Province` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `id_country` INT NULL,
  `Provincecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`City` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `zipcode` VARCHAR(10) NULL,
  `id_province` INT NULL,
  `id_country` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Product_Gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Product_Gallery` (
  `id` INT NOT NULL,
  `image` VARCHAR(255) NULL,
  `id_product` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`User_medal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`User_medal` (
  `id_user` INT NOT NULL,
  `id_medal` INT NULL,
  `expiry` DATETIME NULL,
  `is_active` TINYINT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Medal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Medal` (
  `id` INT NOT NULL,
  `name` VARCHAR(145) NULL,
  `icon_img` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `condition` VARCHAR(255) NULL,
  `created_by` INT NULL,
  `created_at` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Product` (
  `id` INT NOT NULL,
  `sku` VARCHAR(45) NULL,
  `slug` VARCHAR(145) NULL,
  `short_description` VARCHAR(255) NULL,
  `long_description` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `price` INT NULL,
  `promo` INT NULL,
  `wholesale_price` INT NULL,
  `initial_quantity` INT NULL,
  `quantity` INT NULL,
  `is_stock` TINYINT NULL,
  `state` INT NULL,
  `id_vendor` INT NULL,
  `id_brand` INT NULL,
  `id_cat1` INT NULL,
  `id_cat2` INT NULL,
  `id_cat3` INT NULL,
  `id_cat_store` INT NULL,
  `created_by` INT NULL,
  `created_at` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Translation` (
  `id` INT NOT NULL,
  `name_ar` VARCHAR(255) NULL,
  `name_fr` VARCHAR(255) NULL,
  `name_en` VARCHAR(255) NULL,
  `name_de` VARCHAR(255) NULL,
  `name_it` VARCHAR(255) NULL,
  `name_ch` VARCHAR(255) NULL,
  `name_jp` VARCHAR(255) NULL,
  `name_kr` VARCHAR(255) NULL,
  `name_es` VARCHAR(255) NULL,
  `name_extra_1` VARCHAR(255) NULL,
  `name_extra_2` VARCHAR(255) NULL,
  `name_extra_3` VARCHAR(255) NULL,
  `id_object` INT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Customer_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Customer_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(145) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Parametres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Parametres` (
  `id` INT NOT NULL,
  `homepage_json` TEXT NULL,
  `product_json` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Feedback` (
  `id` INT NOT NULL,
  `comment` VARCHAR(255) NULL,
  `rating` DOUBLE NULL,
  `image` VARCHAR(255) NULL,
  `Id_customer` INT NULL,
  `id_order` INT NULL,
  `id_vendor` INT NULL,
  `id_product` INT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Complaint` (
  `id` INT NOT NULL,
  `id_customer` INT NULL,
  `id_vendor` INT NULL,
  `by_customer` TINYINT NULL,
  `title` VARCHAR(255) NULL,
  `message` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Response` (
  `id` INT NOT NULL,
  `message` VARCHAR(255) NULL,
  `id_complaint` INT NULL,
  `id_admin` INT NULL,
  `id_user` INT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Order` (
  `id` INT NOT NULL,
  `state` INT NULL,
  `total_price` INT NULL,
  `total_promo_price` INT NULL,
  `total_with_promo` INT NULL,
  `total_shipping` INT NULL,
  `total_tax` INT NULL,
  `total_amount` INT NULL,
  `website_comission` INT NULL,
  `customer_name` VARCHAR(255) NULL,
  `customer_country` VARCHAR(45) NULL,
  `customer_phone` VARCHAR(45) NULL,
  `customer_email` VARCHAR(45) NULL,
  `comment` VARCHAR(255) NULL,
  `id_customer` INT NULL,
  `id_vendor` INT NULL,
  `created_at` DATETIME NULL,
  `Finished_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Order_item` (
  `id` INT NOT NULL,
  `product_name` VARCHAR(255) NULL,
  `quantity` INT NULL,
  `price` INT NULL,
  `total_price` INT NULL,
  `comment` VARCHAR(255) NULL,
  `id_product` INT NULL,
  `id_order` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Discount` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `cupon` VARCHAR(45) NULL,
  `value` INT NULL,
  `type` INT NULL,
  `date_start` DATETIME NULL,
  `date_end` DATETIME NULL,
  `state` INT NULL,
  `id_category_customer` INT NULL,
  `id_product` INT NULL,
  `id_vendor` INT NULL,
  `id_customer` INT NULL,
  `id_category_product` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Product_Option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Product_Option` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `is_multi` TINYINT NULL,
  `is_required` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_db`.`Option_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Option_item` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `price` INT NULL,
  `image` VARCHAR(255) NULL,
  `id_option` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
